### ISSUE TITLE
Add CPU/GPU benchmark methodology details to user guide and huggingface space

### ISSUE THREAD

**Issue by jeremyfowers** [groq/mlagility#321]
Specific user questions:
1) Where (in the system) is this latency measured?
2) If this is measured at the CPU, I believe we could get higher throughput than 1/latency by pipelining (essentially overlapping communication and compute).  Do you agree?  If so, what are the corresponding throughput numbers?

**Comment by ramkrishna2910** [comment]
CPU: Latency measurements are done using standard timer libraries for the inference call.
GPU: Latency measurements are done by `trtexec` (benchmarking tool from NVIDIA TensorRT). Following is the description of the measuremets provided.
GPU Compute Time: the GPU latency to execute the kernels for a query.
Total GPU Compute Time: the summation of the GPU Compute Time of all the queries. If this is significantly shorter than Total Host Walltime, the GPU may be under-utilized because of host-side overheads or data transfers.
Throughput: the observed throughput computed by dividing the number of queries by the Total Host Walltime. If this is significantly lower than the reciprocal of GPU Compute Time, the GPU may be under-utilized because of host-side overheads or data transfers.
Enqueue Time: the host latency to enqueue a query. If this is longer than GPU Compute Time, the GPU may be under-utilized. or host-to-device data transfers for input tensors of a single query. or device-to-host data transfers for output tensors of a single query.
Latency: the summation of H2D Latency, GPU Compute Time, and D2H Latency. This is the latency to infer a single query.
End-to-End Host Latency: the duration from when the H2D of a query is called to when the D2H of the same query is completed, which includes the latency to wait for the completion of the previous query. This is the latency of a query if multiple queries are enqueued consecutively.

**Comment by jeremyfowers** [comment]
@ramkrishna2910 thanks! Can you provide more detail for CPU?
- How is throughput measured?
- How many samples are run?
- Warm cache or cold cache?
- How is latency timed? Is it the time for one inference, or `time for N inferences / N`?
